/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

// подключаем библиотеку opencv.hpp
#include "opencv2/opencv.hpp"
/* Header for class com_example_ayudatsenko_lesson32opencvfacedetection_OpenCV */

// указываем пространство имен
using namespace cv;

#ifndef _Included_com_example_ayudatsenko_lesson32opencvfacedetection_OpenCV
#define _Included_com_example_ayudatsenko_lesson32opencvfacedetection_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ayudatsenko_lesson32opencvfacedetection_OpenCV
 * Method:    faceDetection
 * Signature: (J)V
 */

// объявляем метод детектирования в header файле
void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_example_ayudatsenko_lesson32opencvfacedetection_OpenCV_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
